<p class="prologue">This article is an expansion of <a href="http://faculty.washington.edu/mhoney/">Michael K. Honey</a>, "Memphis Sanitation Strike (1968)" in the Oxford Encyclopedia of American Business, Labor and Economic History, edited by Melvin Dubofsky (New York and Oxford: Oxford University Press, 2013).</p>

<div class="prev-next">
<p class="previous"><a href="/iamaman">Home</a></p>
<p class="next"><a href="panel2">Next</a></p>
</div>

<div class="panel_text">

<div id="honey">
<p><span class="dropcap">On&nbsp; February&nbsp; 1,&nbsp; 1968,&nbsp; a&nbsp; faulty&nbsp; packing&nbsp; ram&nbsp; on&nbsp; a&nbsp; "wiener&nbsp; barrel"&nbsp; sanitation&nbsp; truck&nbsp; in&nbsp; Memphis&nbsp; crushed&nbsp; to&nbsp; death&nbsp; Echol&nbsp; Cole&nbsp; and&nbsp; Robert&nbsp; Walker.</span></p>

<p>These two African American men had been riding in the truck's garbage bin to stay out of the rain.  The City of Memphis under Mayor Henry Loeb, as a fiscal asusterity measure, had continued to use such outmoded equipment in the Public Works Department when it should have been junked. The city paid most of its 1,300 sanitation workers a minimum wage of one dollar and sixty cents per hour; they worked until their routes were done, often putting in sixty hours a week at forty hours of pay; some forty percent of them were poor enough to draw welfare while working full-time jobs. The city hired and fired unskilled black workers at will, provided them with no showers or other sanitary facilities, no access to supervisory jobs, no rights and no respect, minimal health and accident insurance.  Cole and Walker, both in their thirties, left behind wives and children with no sources of income.</p>

<p>T.O. Jones had tried to organize the workers into a union to change these conditions but Mayor Loeb refused to recognize or bargain with a union or deduct union dues. As in our own time, Loeb was a pro-business Republican who sought to block public employee unions and destroy them in the private sector as well.  This left working people with no means to advance their interests. In previous years, workers had advanced to a "middle class" status through the industrial unions of the Congress of Industrial Organizations (CIO), and black workers in Memphis had overcome Jim Crow barriers to better jobs and wage classifications through union activism. However, after the rise of the CIO (1935-1955) organizing had stalled, manufacturing and unionization both began their long decline, and living standards for workers stagnated or declined. By 1968, Sanitation workers were part of the African American community's vast working poor, doing full-time work at part-time wages. A public employee union was the only means to resolve their plight.</p>

<p>A few days after the deaths of Cole and Walker, Public Works supervisors added insult to injury when they sent sewer and drain workers home with no wages during a rain storm -- while white supervisors stayed at work and drew their full pay with little to do. After a Sunday night meeting to air their grievances, the sanitation workers went on strike on Monday, February 12, Abraham Lincoln's birthday. Jones, leader of Local 1733 of the American Federation of State, County, and Municipal Workers (AFSCME) did not ask for approval from his national office. He knew it would not approve and had no strike fund with which to support Memphis workers. Mayor Loeb responded by threatening to permanently replace the strikers, while city police escorted garbage trucks and scabs to break the strike. During the next six weeks, the police would attack workers and their supporters with clubs and mace, not once but twice. The strike became a huge battle over not just the worker's right to join a union, but over the dignity and self-respect of the city's black citizens.</p>

<p>While reluctant to join the battle at first, the city's black community, some forty percent of the city's population of half a million, saw the violent police response and the Mayor's hard line against the workers as a carryover of the "plantation mentality" of white racism that so many people had endured in the mid-South's history of slavery and segregation. When workers put up picket signs declaring "I Am a Man," everyone knew exactly what they were talking about. Rev. James Lawson, Henry Starks and other black ministers opened their churches to nightly rallies; Maxine Smith, Samuel Kyles, and others in the National Association for the Advancement of Colored People (NAACP) took a leading role; AFSCME organized mass picket lines and mass demonstrations confronting the Mayor and city council; black and white women boycotted downtown merchants; the Memphis Labor Council (AFL-CIO) passed a resolution and held demonstrations of support, led by Tommy Powell and Bill Ross; the United Rubber Workers union opened its hall for daily meetings; black students walked out of school to attend demonstrations; Black Power advocates called the Invaders threatened to escalate to incendiary tactics; AFSCME International President Jerry Wurf, Bill Lucy, Jesse Epps and other staff members of the international put everything the union had on the line to support the strike; numerous members of Local 1733, including Joe Warren, Taylor Rogers, James Robinson, and other workers too numerous to name carried the battle forward through twice daily marches, evening church rallies, and continual picket lines. Notably, even though the strikers were all male, women in both the black and the white communities played crucial roles through family, church, and community organizations in providing food, clothing and shelter for striking families and in spearheading a consumer boycott that devastated downtown merchants. Historian Laurie B. Green shows how women's networks built up various movements leading to the strike and continued to play a crucial role during and afterward. (For a list of some of the remarkable individuals involved in the strike, see the "Main Individuals and Organizations" appendix to Going Down Jericho Road).</p>

<p>The Memphis strike created a true mass movement and perhaps the best example of the coalition of labor, the church, civil rights, and students that Martin Luther King, Jr., and generations of organizers had sought. The national media largely blocked out the strike, however, while the Memphis Commercial Appeal grossly distorted the facts and the issues and the white-dominated media largely refused to tell the worker and the union side of the story to the public. Civil rights leaders Roy Wilkins and Bayard Rustin came to speak in hopes of getting national attention and clarifying the issues. But the strike did not get much national attention until March 18, when Dr. King gave an impassioned speech at a packed Charles Mason Temple, in probably the largest indoor mass gathering in the South during the civil rights era. King declared, "all labor has dignity" and made Memphis part of his Poor People's Campaign to take impoverished people to the nation's capitol to demand that Congress shift its war spending to address health care, jobs, housing, education, and other human needs.</p>

<p>King pledged to return to lead a general strike of black workers and students against the city but when he did so on March 28, provocateurs and adventurists broke windows and the Memphis police attacked. Chaos, indiscriminate beatings, and the police murder of a defenseless sixteen-year-old named Larry Payne ensued. King returned again, intending to lead a peaceful mass march but an assassin murdered him with a single bullet on April 4. Mass insurrections took place in over 100 cities and forced the largest mass mobilization of the American military to suppress domestic rebellion since the Civil War. Ultimately the Federal Bureau of Investigation (FBI) captured an escaped convict named James Earl Ray, who confessed to the assassination in a plea bargain for his life. Few people in the black community believed he acted alone and many doubted whether he did it at all. The actions of the FBI, Military Intelligence, and the Memphis Police in the constant surveillance and harassment of Dr. King raised suspicions, especially in subsequent years as Congressional investigations exposed a widespread conspiracy by law enforcement authorities to disrupt, divide and destroy the black freedom movement.</p>

<p>Despite the national crisis following Dr. King's death, Mayor Loeb still refused to sign a union contract or accept deduction of union dues from worker paychecks. As an inveterate segregationist, as a previous employer of low wage black laundry workers in his family's business, and as a conservative Republican, he was unable to make any compromises with a union of black public employees -- even under pressure from the President of the United States Lyndon Baines Johnson, Tennessee Governor Buford Ellington, and the U.S. Labor Department, who sent a special emissary dispatched by the President to resolve the crisis. Finally, a very reluctant City Council signed an agreement with AFSCME Local 1733 on April 16. It did not grant a union shop, something that left the local weakened for years to come, but it granted collection of union dues and basic collective bargaining rights.</p>

<p>The Memphis strike had widespread and historic repercussions, both negative and positive. King's assassination left his Poor People's Campaign to flounder; six weeks later, the murder of presidential candidate Robert F. Kennedy provided a crushing blow to the social change movements of the 1960s.  However, the example of the strike's success activated municipal, hospital and service workers across the South; AFSCME, viewing the strike as a seminal moment, evolved into one of the largest unions in the United States, and a powerhouse in electoral politics. So much so, in fact, that the Republican Governor of Wisconsin Scott Walker pulled out all the stops in 2010 in an effort to destroy public employee unionism and remove it as a potent political ally of Democratic President Barack Obama. Although historians once viewed the Memphis story largely as the backdrop for King's assassination, many now consider the wider implications of the rise of AFSCME and his role in helping to promote the labor movement. More recent historical treatments have seen this civil rights strike as the spark for a remarkable community and labor movement and as part of the black freedom struggle's turn toward economic justice and union rights for racial minorities and the working poor.  This historical treatment of the strike as an epochal event also represents a turn toward seeing Dr. King as a union and human rights and labor advocate as well as a civil rights leader, one whose message continues to resound in the struggles of the working poor in the globalized economy and anti-union political climate of the twenty-first century.</p>

<p class="epilogue">For a powerful expansion on the role of black women in the movement, see Laurie B. Green, Battling the Plantation Mentality: Memphis and the Black Freedom Struggle  (Chapel Hill: University of North Carolina Press, 2007). Honey's Going Down Jericho Road: The Memphis Strike, Martin Luther King's Last Campaign (New York: W.W. Norton, 2007), provides the definitive history of the strike and King's role in it. Joan Beifuss, At the River I Stand (Memphis: B and W Press, 1985), provided the first comprehensive account based on the mass of oral history interviews and media resources, collected by Beifuss and others in the Memphis Search for Meaning committee, housed at the Mississippi Valley Collection of the University of Memphis library. For King's union speeches, collected and edited by Michael K. Honey, see Martin Luther King, Jr., All Labor Has Dignity (Boston: Beacon Press, 2011). For in-depth interviews with Memphis black workers, including sanitation workers, see Honey, Black Workers Remember: An Oral History of Segregation, Unionism, and the Freedom Struggle (Berkeley: University of California Press, 1997). For the history of the CIO in the South and Memphis leading up to the strike see Honey, Southern Labor and Black Civil Rights: Organizing Memphis Workers (Urbana: University of Illinois Press, 1993). For an entry into other works on labor, see Dubofsky's Oxford Dictionary cited above.</p>

</div>


<div class="prev-next">
<p class="previous"><a href="/iamaman">Home</a></p>
<p class="next"><a href="panel2">Next</a></p>
</div>

</div>
